# Generated by Django 4.0.4 on 2022-07-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_course_lesson_courseteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteachers',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
