# Generated by Django 4.0.4 on 2022-07-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_courseteachers_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseteachers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courseteachers',
            name='updated_at',
        ),
    ]
